-- 1. favorites 테이블 생성
CREATE TABLE IF NOT EXISTS public.favorites (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    campsite_id text NOT NULL,
    device_id text NOT NULL,
    status text NOT NULL CHECK (status IN ('planned', 'visited')),
    created_at timestamp with time zone DEFAULT now()
);

-- 2. 해당 테이블에 대한 RLS(Row Level Security) 설정 해제 또는 정책 추가
-- 간편한 연동 및 테스트를 위해 RLS를 해제하려면 아래 줄을 사용하세요:
ALTER TABLE public.favorites DISABLE ROW LEVEL SECURITY;

-- (선택 사항) 만약 RLS를 활성화하고 익명(Anonymous) 접근 정책을 추가하려면 아래 주석을 해제하고 실행하세요:
/*
ALTER TABLE public.favorites ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow anonymous select" ON public.favorites FOR SELECT TO anon USING (true);
CREATE POLICY "Allow anonymous insert" ON public.favorites FOR INSERT TO anon WITH CHECK (true);
CREATE POLICY "Allow anonymous update" ON public.favorites FOR UPDATE TO anon USING (true) WITH CHECK (true);
CREATE POLICY "Allow anonymous delete" ON public.favorites FOR DELETE TO anon USING (true);
*/
